# примеры API-запросов

@baseUrl = http://127.0.0.1:8000/api

# получение датчиков
GET {{baseUrl}}/list/
Content-Type: application/json

###

# создание датчика
POST {{baseUrl}}/create/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# обновление датчика
PATCH {{baseUrl}}/change/1/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurement/1/
Content-Type: application/json

{
  "sensor": 1,
  "temperature": 22.3
}

###

# получение информации по датчику
GET {{baseUrl}}/detail/1/
Content-Type: application/json
